### ISSUE TITLE
Error after restarting each

### ISSUE THREAD

**Issue by imtorich** [PlazmaMC/Plazma#56]
Reboot the server, and blows out an error, it happens very rarely, and immediately after a full start of the server.
This error is on both Paper and Plazma.
At the moment it is on Plazma.
> ver
[14:31:11 INFO]: Checking version, please wait...
[14:31:12 INFO]: Current: git-Plazma-"74c593f" (MC: 1.20.1)*
Previous: git-Paper-169 (MC: 1.20.1)
* You are 5 version(s) behind

Error:
>
[23:26:10 ERROR]: Caught previously unhandled exception :
[23:26:10 ERROR]: Paper Async Command Builder Thread Pool - 0
java.util.ConcurrentModificationException: null
        at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]
        at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]
        at net.minecraft.commands.Commands.fillUsableCommands(Commands.java:487) ~[?:?]
        at net.minecraft.commands.Commands.sendAsync(Commands.java:451) ~[?:?]
        at net.minecraft.commands.Commands.lambda$sendCommands$4(Commands.java:424) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by IPECTER** [comment]
Dont report this to Plazma.
Its your data problem 
ex)datapack, plugin, etc
